export const HELLO_REDUX = 'HELLO_REDUX';
export const START_TEST = 'START_TEST';
export const ERROR_GET_TEST = 'ERROR_GET_TEST';
export const SELECT_SINGLE_CHOICE = 'SELECT_SINGLE_CHOICE';
export const SELECT_MULTIPLE_CHOICE = 'SELECT_MULTIPLE_CHOICE';
export const UNSELECT_MULTIPLE_CHOICE = 'UNSELECT_MULTIPLE_CHOICE';
